// import "./components/get-graphs-data";
import "./components/hero-radial-1c";
import "./components/hero-radial-bitrix";
import "./components/switch";
import "./components/theme-change";
import "./components/stats-radial-conversy";
import "./components/stats-radial-graph";
import "./components/contacts-slider-1c";
import "./components/contacts-slider-bitrix";
import "./components/date-buttons";
import "./components/buttons-height";
import "./components/graphs-data-controller";
import "./components/loader";
import "./components/history-anim";
